### PR TITLE
added scroll to top button

### PR DESCRIPTION
**Pull request by itsOmSarraf**

### CODE REVIEW

**Comment by Ankit-11525** [comment]
Please resolve the conflicts

**Comment by Ankit-11525** [comment]
Please deploy at your end as it also helps in future

**Comment by itsOmSarraf** [comment]
Sure. resolving

**Comment by Ankit-11525** [comment]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/Ankit-11525/e-commerce_redstore.github.io/pull/113/conflicts) or the  to resolve conflicts.
Conflicting files
allproducts.html
style.css

**Pull request closed without merging**
